### ISSUE TITLE
Suggestion: Title color

### ISSUE THREAD

**Issue by SzewcuDratewka** [RudeNudeDude/GitHub_crash_course#1]
I think it looks better if the title color looks more rose.

``` css
h1 {
  color: #a30a51;
}
```
